// not sure this is funny or bad taste...yet to be decided

const adjectives = [
  "Aromatic",
  "Bubbly",
  "Buttery",
  "Caramelized",
  "Charred",
  "Cheery",
  "Citrusy",
  "Creamy",
  "Crispy",
  "Crunchy",
  "Dazzling",
  "Delightful",
  "Divine",
  "Earthy",
  "Exotic",
  "Fiery",
  "Fluffy",
  "Fragrant",
  "Fresh",
  "Glorious",
  "Golden",
  "Gourmet",
  "Hearty",
  "Homemade",
  "Infused",
  "Juicy",
  "Luscious",
  "Peppery",
  "Piquant",
  "Refreshing",
  "Rich",
  "Rustic",
  "Savory",
  "Silky",
  "Sizzling",
  "Smoky",
  "Spiced",
  "Spicy",
  "Succulent",
  "Sweet",
  "Tangy",
  "Toasty",
  "Velvety",
  "Wholesome",
  "Zesty",
  "Zingy",
  "Zippy",
];
const methods = [
  "Baked",
  "Blanched",
  "Blended",
  "Braised",
  "Broiled",
  "Candied",
  "Chilled",
  "Crushed",
  "Cured",
  "Deconstructed",
  "Dehydrated",
  "Diced",
  "Drizzled",
  "Emulsified",
  "Fermented",
  "Folded",
  "Fried",
  "Fused",
  "Garnished",
  "Glazed",
  "Gratinated",
  "Grilled",
  "Infused",
  "Layered",
  "Macerated",
  "Marinated",
  "Mashed",
  "Microwaved",
  "Muddled",
  "Percolated",
  "Pickled",
  "Poached",
  "Pressure-Cooked",
  "Pulverized",
  "Roasted",
  "Sauteed",
  "Seared",
  "Shredded",
  "Simmered",
  "Sliced",
  "Smoked",
  "Sprouted",
  "Steamed",
  "Stewed",
  "Stir-Fried",
  "Sun-Dried",
  "Toasted",
  "Whipped",
  "Whisked",
];
const dishes = [
  "Baklava",
  "Bakso",
  "Bao",
  "Biryani",
  "Blintz",
  "Borscht",
  "Bruschetta",
  "Burger",
  "Burrito",
  "Bánh mì",
  "Bún bò Huế",
  "Bún chả",
  "Bún mắm",
  "Bún riêu",
  "Cao lầu",
  "Casserole",
  "Cașcaval",
  "Ceviche",
  "Chowder",
  "Chutney",
  "Cháo",
  "Ciorbă",
  "Crepes",
  "Croissant",
  "Curry",
  "Currywurst",
  "Cơm tấm",
  "Dumpling",
  "Döner",
  "Enchilada",
  "Fajita",
  "Falafel",
  "Focaccia",
  "Fondue",
  "Fondue",
  "Frittata",
  "Gado-gado",
  "Gazpacho",
  "Gnocchi",
  "Goulash",
  "Guacamole",
  "Gỏi cuốn",
  "Gỏi gà",
  "Gỏi đu đủ",
  "Hummus",
  "Kebab",
  "Ketoprak",
  "Lasagna",
  "Martabak",
  "Meatloaf",
  "Mici",
  "Moussaka",
  "Mămăligă",
  "Nasi goreng",
  "Nasi uduk",
  "Noodles",
  "Omelette",
  "Paella",
  "Pancake",
  "Pasta",
  "Phở",
  "Pie",
  "Pizza",
  "Poutine",
  "Quiche",
  "Ramen",
  "Rawon",
  "Rendang",
  "Ribs",
  "Risotto",
  "Salad",
  "Salată de boeuf",
  "Salată de vinete",
  "Sambal",
  "Sandwich",
  "Sarmale",
  "Sate",
  "Schnitzel",
  "Soto",
  "Soup",
  "Steak",
  "Supă de pui",
  "Sushi",
  "Taco",
  "Tapas",
  "Tart",
  "Tiramisu",
  "Tocană",
  "Tofu",
  "Waffles",
  "Xôi",
  "Zacuscă",
];

// Function to randomly select an item from a list
function getRandomItem(list: string[]) {
  return list[Math.floor(Math.random() * list.length)];
}

// Function to generate a random dish name
export function generateDishName() {
  const adjective = getRandomItem(adjectives);
  const method = getRandomItem(methods);
  const dish = getRandomItem(dishes);
  return `${adjective} ${method} ${dish}`;
}
